[package]
name = "postman-request"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
postman-http = { path = "../postman-http" }
reqwest = { version = "0.12", features = [
    "brotli",
    "cookies",
    "deflate",
    "gzip",
    "multipart",
] }
tokio = { version = "1", features = ["fs", "time"] }



[dev-dependencies]
